<a href="https://colab.research.google.com/github/ginnelalikitha/python/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# pandas

In [ ]:
import pandas  as pd
Mydataset={
    'Name':["Likitha","Elena","Zoya","Rithu","Ponnu","Firoj"],
    'Rollno':[12,15,43,62,29,20],
    'Marks':[45,50,49,40,35,38],
    'Subject':["Telugu","English","Maths","Science","Telugu","Social"]
}
myvar = pd.DataFrame(Mydataset)
print(myvar)

      Name  Rollno  Marks  Subject
0  Likitha      12     45   Telugu
1    Elena      15     50  English
2     Zoya      43     49    Maths
3    Rithu      62     40  Science
4    Ponnu      29     35   Telugu
5    Firoj      20     38   Social

In [ ]:
myvar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Rollno   6 non-null      int64
 2   Marks    6 non-null      int64
 3   Subject  6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
myvar.sample(2)

    Name  Rollno  Marks  Subject
1  Elena      15     50  English
3  Rithu      62     40  Science

In [ ]:
myvar.tail()

    Name  Rollno  Marks  Subject
1  Elena      15     50  English
2   Zoya      43     49    Maths
3  Rithu      62     40  Science
4  Ponnu      29     35   Telugu
5  Firoj      20     38   Social

In [ ]:
myvar.shape

(6, 4)

In [ ]:
myvar[['Name','Marks']]

      Name  Marks
0  Likitha     45
1    Elena     50
2     Zoya     49
3    Rithu     40
4    Ponnu     35
5    Firoj     38

In [ ]:
myvar[myvar['Marks']>40]

      Name  Rollno  Marks  Subject
0  Likitha      12     45   Telugu
1    Elena      15     50  English
2     Zoya      43     49    Maths

In [ ]:
myvar[(myvar['Marks']>40) & (myvar['Rollno']>20)]

   Name  Rollno  Marks Subject
2  Zoya      43     49   Maths

In [ ]:
myvar[(myvar['Marks']>40) | (myvar['Rollno']>20)]

      Name  Rollno  Marks  Subject
0  Likitha      12     45   Telugu
1    Elena      15     50  English
2     Zoya      43     49    Maths
3    Rithu      62     40  Science
4    Ponnu      29     35   Telugu

In [ ]:
myvar.describe()

          Rollno      Marks
count   6.000000   6.000000
mean   30.166667  42.833333
std    19.198090   6.112828
min    12.000000  35.000000
25%    16.250000  38.500000
50%    24.500000  42.500000
75%    39.500000  48.000000
max    62.000000  50.000000

In [ ]:
myvar['Marks'].mean()

np.float64(42.833333333333336)

In [ ]:
myvar['Marks'].max()

50

In [ ]:
myvar['Marks'].min()

35

In [ ]:
modified_myvar=myvar.copy()
modified_myvar

      Name  Rollno  Marks  Subject
0  Likitha      12     45   Telugu
1    Elena      15     50  English
2     Zoya      43     49    Maths
3    Rithu      62     40  Science
4    Ponnu      29     35   Telugu
5    Firoj      20     38   Social

In [ ]:
modified_myvar.head()

      Name  Rollno  Marks  Subject
0  Likitha      12     45   Telugu
1    Elena      15     50  English
2     Zoya      43     49    Maths
3    Rithu      62     40  Science
4    Ponnu      29     35   Telugu

In [ ]:
modified_myvar['Average']=modified_myvar['Marks']/5
modified_myvar.head()

      Name  Rollno  Marks  Subject  Average
0  Likitha      12     45   Telugu      9.0
1    Elena      15     50  English     10.0
2     Zoya      43     49    Maths      9.8
3    Rithu      62     40  Science      8.0
4    Ponnu      29     35   Telugu      7.0

In [ ]:
modified_myvar['Marks_state']=modified_myvar['Marks'].apply(lambda x:'pass'if x>20 else'fail')
modified_myvar.head()

      Name  Rollno  Marks  Subject  Average Marks_state
0  Likitha      12     45   Telugu      9.0        pass
1    Elena      15     50  English     10.0        pass
2     Zoya      43     49    Maths      9.8        pass
3    Rithu      62     40  Science      8.0        pass
4    Ponnu      29     35   Telugu      7.0        pass

#sorting

In [ ]:
myvar.sort_values('Rollno')

      Name  Rollno  Marks  Subject
0  Likitha      12     45   Telugu
1    Elena      15     50  English
5    Firoj      20     38   Social
4    Ponnu      29     35   Telugu
2     Zoya      43     49    Maths
3    Rithu      62     40  Science

In [ ]:
myvar.sort_values('Rollno',ascending=False)

      Name  Rollno  Marks  Subject
3    Rithu      62     40  Science
2     Zoya      43     49    Maths
4    Ponnu      29     35   Telugu
5    Firoj      20     38   Social
1    Elena      15     50  English
0  Likitha      12     45   Telugu

#loc,iloc

In [ ]:
myvar.loc[0]

Name       Likitha
Rollno          12
Marks           45
Subject     Telugu
Name: 0, dtype: object

In [ ]:
myvar.loc[[0,2,4],['Name','Marks']]

      Name  Marks
0  Likitha     45
2     Zoya     49
4    Ponnu     35

In [ ]:
myvar['Marks']>40

0     True
1     True
2     True
3    False
4    False
5    False
Name: Marks, dtype: bool

In [ ]:
myvar.loc[myvar['Marks']>40]

      Name  Rollno  Marks  Subject
0  Likitha      12     45   Telugu
1    Elena      15     50  English
2     Zoya      43     49    Maths

In [ ]:
myvar.iloc[[0,2,4],[0,2]]

      Name  Marks
0  Likitha     45
2     Zoya     49
4    Ponnu     35

In [ ]:
myvar.iloc[[0],[0]]

      Name
0  Likitha

In [ ]:
myvar.iloc[0:3 , 0:3]

      Name  Rollno  Marks
0  Likitha      12     45
1    Elena      15     50
2     Zoya      43     49

#Groupby

In [ ]:
myvar.groupby('Name')['Marks'].count()

Name
Elena      1
Firoj      1
Likitha    1
Ponnu      1
Rithu      1
Zoya       1
Name: Marks, dtype: int64

In [ ]:
myvar.groupby(['Name','Rollno'])['Marks'].agg(['mean','min','max','count'])

                mean  min  max  count
Name    Rollno
Elena   15      50.0   50   50      1
Firoj   20      38.0   38   38      1
Likitha 12      45.0   45   45      1
Ponnu   29      35.0   35   35      1
Rithu   62      40.0   40   40      1
Zoya    43      49.0   49   49      1

#pivot

In [ ]:
import pandas  as pd
store={
'product':['facewash','sunscreen','serum','kumkumadi thailam','facemask','moisturizer'],
'Brands':['hyphen','foxtale','dermaco','naturals','korean','nivea'],
        'price':[250,330,450,3000,120,400],
}
df = pd.DataFrame(store)
print(df)

             product    Brands  price
0           facewash    hyphen    250
1          sunscreen   foxtale    330
2              serum   dermaco    450
3  kumkumadi thailam  naturals   3000
4           facemask    korean    120
5        moisturizer     nivea    400

In [ ]:
df.groupby('product')['price'].sum()

product
facemask              120
facewash              250
kumkumadi thailam    3000
moisturizer           400
serum                 450
sunscreen             330
Name: price, dtype: int64

In [ ]:
df.groupby('Brands')['price'].sum()

Brands
dermaco      450
foxtale      330
hyphen       250
korean       120
naturals    3000
nivea        400
Name: price, dtype: int64

In [ ]:
#create pivot table
pivot=df.pivot_table(
    index='product',
    columns='Brands',
    values='price',
    aggfunc='sum',
    margins=True,
    margins_name='Total'
)

Brands             dermaco  foxtale  hyphen  korean  naturals  nivea  Total
product
facemask               NaN      NaN     NaN   120.0       NaN    NaN    120
facewash               NaN      NaN   250.0     NaN       NaN    NaN    250
kumkumadi thailam      NaN      NaN     NaN     NaN    3000.0    NaN   3000
moisturizer            NaN      NaN     NaN     NaN       NaN  400.0    400
serum                450.0      NaN     NaN     NaN       NaN    NaN    450
sunscreen              NaN    330.0     NaN     NaN       NaN    NaN    330
Total                450.0    330.0   250.0   120.0    3000.0  400.0   4550

In [ ]:
pivot

Brands             dermaco  foxtale  hyphen  korean  naturals  nivea  Total
product
facemask               NaN      NaN     NaN   120.0       NaN    NaN    120
facewash               NaN      NaN   250.0     NaN       NaN    NaN    250
kumkumadi thailam      NaN      NaN     NaN     NaN    3000.0    NaN   3000
moisturizer            NaN      NaN     NaN     NaN       NaN  400.0    400
serum                450.0      NaN     NaN     NaN       NaN    NaN    450
sunscreen              NaN    330.0     NaN     NaN       NaN    NaN    330
Total                450.0    330.0   250.0   120.0    3000.0  400.0   4550

#crosstab

In [ ]:
ct=pd.crosstab(df['product'],df['price'])
ct

price              120   250   330   400   450   3000
product
facemask              1     0     0     0     0     0
facewash              0     1     0     0     0     0
kumkumadi thailam     0     0     0     0     0     1
moisturizer           0     0     0     1     0     0
serum                 0     0     0     0     1     0
sunscreen             0     0     1     0     0     0

#merge

In [ ]:
import pandas as pd
store={
'product':['facewash','sunscreen','serum','kumkumadi thailam','facemask','moisturizer'],
'Brands':['hyphen','foxtale','dermaco','naturals','korean','nivea'],
        'price':[250,330,450,3000,120,400],
        'Marks':[45,50,49,40,35,38]
}
df = pd.DataFrame(store)
df

             product    Brands  price  Marks
0           facewash    hyphen    250     45
1          sunscreen   foxtale    330     50
2              serum   dermaco    450     49
3  kumkumadi thailam  naturals   3000     40
4           facemask    korean    120     35
5        moisturizer     nivea    400     38

In [ ]:
Mydataset={
    'Name':["Likitha","Elena","Zoya","Rithu","Ponnu","Firoj"],
    'Rollno':[12,15,43,62,29,20],
    'Marks':[45,50,49,40,35,38],
    'Subject':["Telugu","English","Maths","Science","Telugu","Social"]
}
myvar = pd.DataFrame(Mydataset)
myvar

      Name  Rollno  Marks  Subject
0  Likitha      12     45   Telugu
1    Elena      15     50  English
2     Zoya      43     49    Maths
3    Rithu      62     40  Science
4    Ponnu      29     35   Telugu
5    Firoj      20     38   Social

In [ ]:
merge=pd.merge(df,myvar,on='Marks')
merge

             product    Brands  price  Marks     Name  Rollno  Subject
0           facewash    hyphen    250     45  Likitha      12   Telugu
1          sunscreen   foxtale    330     50    Elena      15  English
2              serum   dermaco    450     49     Zoya      43    Maths
3  kumkumadi thailam  naturals   3000     40    Rithu      62  Science
4           facemask    korean    120     35    Ponnu      29   Telugu
5        moisturizer     nivea    400     38    Firoj      20   Social

In [ ]:
concatenate=pd.concat([df,myvar],ignore_index=True)
concatenate

              product    Brands   price  Marks     Name  Rollno  Subject
0            facewash    hyphen   250.0     45      NaN     NaN      NaN
1           sunscreen   foxtale   330.0     50      NaN     NaN      NaN
2               serum   dermaco   450.0     49      NaN     NaN      NaN
3   kumkumadi thailam  naturals  3000.0     40      NaN     NaN      NaN
4            facemask    korean   120.0     35      NaN     NaN      NaN
5         moisturizer     nivea   400.0     38      NaN     NaN      NaN
6                 NaN       NaN     NaN     45  Likitha    12.0   Telugu
7                 NaN       NaN     NaN     50    Elena    15.0  English
8                 NaN       NaN     NaN     49     Zoya    43.0    Maths
9                 NaN       NaN     NaN     40    Rithu    62.0  Science
10                NaN       NaN     NaN     35    Ponnu    29.0   Telugu
11                NaN       NaN     NaN     38    Firoj    20.0   Social