<a href="https://colab.research.google.com/github/ginnelalikitha/python/blob/main/practicepandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#practice

In [ ]:
import pandas as pd
dataset={
    'cast':['matt','bonnie','elena','jermey','damon','stefan','tyler','klaus','elijah','rebekah','enzo','marcel'],
    'series':['vampire diaries','the originals','twilight','meg','got','arafta','my demon','first frost','sunlight','shore','zombie','israel'],
    'networth':[2,2.5,1,6,9,10,2.8,11,15,13.5,12,25],
    'properties':[5,7,2,9,10,18,45,32,68,10,14,23]

}
df=pd.DataFrame(dataset)
df

       cast           series  networth  properties
0      matt  vampire diaries       2.0           5
1    bonnie    the originals       2.5           7
2     elena         twilight       1.0           2
3    jermey              meg       6.0           9
4     damon              got       9.0          10
5    stefan           arafta      10.0          18
6     tyler         my demon       2.8          45
7     klaus      first frost      11.0          32
8    elijah         sunlight      15.0          68
9   rebekah            shore      13.5          10
10     enzo           zombie      12.0          14
11   marcel           israel      25.0          23

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   cast        12 non-null     object
 1   series      12 non-null     object
 2   networth    12 non-null     float64
 3   properties  12 non-null     int64
dtypes: float64(1), int64(1), object(2)
memory usage: 516.0+ bytes

In [ ]:
df.head()

     cast           series  networth  properties
0    matt  vampire diaries       2.0           5
1  bonnie    the originals       2.5           7
2   elena         twilight       1.0           2
3  jermey              meg       6.0           9
4   damon              got       9.0          10

In [ ]:
df.tail()

       cast       series  networth  properties
7     klaus  first frost      11.0          32
8    elijah     sunlight      15.0          68
9   rebekah        shore      13.5          10
10     enzo       zombie      12.0          14
11   marcel       israel      25.0          23

In [ ]:
df.sample(3)

    cast       series  networth  properties
2  elena     twilight       1.0           2
4  damon          got       9.0          10
7  klaus  first frost      11.0          32

In [ ]:
df.shape

(12, 4)

In [ ]:
df[['series','networth']]

             series  networth
0   vampire diaries       2.0
1     the originals       2.5
2          twilight       1.0
3               meg       6.0
4               got       9.0
5            arafta      10.0
6          my demon       2.8
7       first frost      11.0
8          sunlight      15.0
9             shore      13.5
10           zombie      12.0
11           israel      25.0

In [ ]:
df['networth'].mean()

np.float64(9.15)

In [ ]:
df['networth'].min()

1.0

In [ ]:
df['networth'].max()

25.0

In [ ]:
df[df['networth']>10]

       cast       series  networth  properties
7     klaus  first frost      11.0          32
8    elijah     sunlight      15.0          68
9   rebekah        shore      13.5          10
10     enzo       zombie      12.0          14
11   marcel       israel      25.0          23

In [ ]:
df[(df['networth']>10) & (df['properties']>20)]

      cast       series  networth  properties
7    klaus  first frost      11.0          32
8   elijah     sunlight      15.0          68
11  marcel       israel      25.0          23

In [ ]:
df[(df['networth']>10) | (df['properties']>20)]

       cast       series  networth  properties
6     tyler     my demon       2.8          45
7     klaus  first frost      11.0          32
8    elijah     sunlight      15.0          68
9   rebekah        shore      13.5          10
10     enzo       zombie      12.0          14
11   marcel       israel      25.0          23

In [ ]:
df.describe()

        networth  properties
count  12.000000   12.000000
mean    9.150000   20.250000
std     6.932598   19.447482
min     1.000000    2.000000
25%     2.725000    8.500000
50%     9.500000   12.000000
75%    12.375000   25.250000
max    25.000000   68.000000

#modified

In [ ]:
modified_df=df.copy()
modified_df

       cast           series  networth  properties
0      matt  vampire diaries       2.0           5
1    bonnie    the originals       2.5           7
2     elena         twilight       1.0           2
3    jermey              meg       6.0           9
4     damon              got       9.0          10
5    stefan           arafta      10.0          18
6     tyler         my demon       2.8          45
7     klaus      first frost      11.0          32
8    elijah         sunlight      15.0          68
9   rebekah            shore      13.5          10
10     enzo           zombie      12.0          14
11   marcel           israel      25.0          23

In [ ]:
modified_df['average_networth']=modified_df['networth']/modified_df['properties']
modified_df

       cast           series  networth  properties  average_networth
0      matt  vampire diaries       2.0           5          0.400000
1    bonnie    the originals       2.5           7          0.357143
2     elena         twilight       1.0           2          0.500000
3    jermey              meg       6.0           9          0.666667
4     damon              got       9.0          10          0.900000
5    stefan           arafta      10.0          18          0.555556
6     tyler         my demon       2.8          45          0.062222
7     klaus      first frost      11.0          32          0.343750
8    elijah         sunlight      15.0          68          0.220588
9   rebekah            shore      13.5          10          1.350000
10     enzo           zombie      12.0          14          0.857143
11   marcel           israel      25.0          23          1.086957

In [ ]:
modified_df['average_properties']=modified_df['properties'].apply(lambda x:'rich'if x>15 else 'medium')
modified_df

,cast,series,networth,properties,average_networth,average_properties
0,matt,vampire diaries,2.0,5,0.400000,medium
1,bonnie,the originals,2.5,7,0.357143,medium
2,elena,twilight,1.0,2,0.500000,medium
3,jermey,meg,6.0,9,0.666667,medium
4,damon,got,9.0,10,0.900000,medium
5,stefan,arafta,10.0,18,0.555556,rich
6,tyler,my demon,2.8,45,0.062222,rich
7,klaus,first frost,11.0,32,0.343750,rich
8,elijah,sunlight,15.0,68,0.220588,rich
9,rebekah,shore,13.5,10,1.350000,medium
10,enzo,zombie,12.0,14,0.857143,medium
11,marcel,israel,25.0,23,1.086957,rich

#sort_values

In [ ]:
df.sort_values('properties'),('networth')

(       cast           series  networth  properties
 2     elena         twilight       1.0           2
 0      matt  vampire diaries       2.0           5
 1    bonnie    the originals       2.5           7
 3    jermey              meg       6.0           9
 4     damon              got       9.0          10
 9   rebekah            shore      13.5          10
 10     enzo           zombie      12.0          14
 5    stefan           arafta      10.0          18
 11   marcel           israel      25.0          23
 7     klaus      first frost      11.0          32
 6     tyler         my demon       2.8          45
 8    elijah         sunlight      15.0          68,
 'networth')

In [ ]:
df.sort_values('networth',ascending=False)

       cast           series  networth  properties
11   marcel           israel      25.0          23
8    elijah         sunlight      15.0          68
9   rebekah            shore      13.5          10
10     enzo           zombie      12.0          14
7     klaus      first frost      11.0          32
5    stefan           arafta      10.0          18
4     damon              got       9.0          10
3    jermey              meg       6.0           9
6     tyler         my demon       2.8          45
1    bonnie    the originals       2.5           7
0      matt  vampire diaries       2.0           5
2     elena         twilight       1.0           2

#loc,iloc

In [ ]:
df.loc[2]

cast             elena
series        twilight
networth           1.0
properties           2
Name: 2, dtype: object

In [ ]:
df.loc[[0,4,6,8,10],['series','networth']]

             series  networth
0   vampire diaries       2.0
4               got       9.0
6          my demon       2.8
8          sunlight      15.0
10           zombie      12.0

In [ ]:
df.iloc[[0,2,4,6,8],[0,3]]

     cast  properties
0    matt           5
2   elena           2
4   damon          10
6   tyler          45
8  elijah          68

#groupby

In [ ]:
df.groupby('series')['properties'].count()

series
arafta             1
first frost        1
got                1
israel             1
meg                1
my demon           1
shore              1
sunlight           1
the originals      1
twilight           1
vampire diaries    1
zombie             1
Name: properties, dtype: int64

In [ ]:
df.groupby(['series','cast'])['properties'].agg(['count','max','min'])

                         count  max  min
series          cast
arafta          stefan       1   18   18
first frost     klaus        1   32   32
got             damon        1   10   10
israel          marcel       1   23   23
meg             jermey       1    9    9
my demon        tyler        1   45   45
shore           rebekah      1   10   10
sunlight        elijah       1   68   68
the originals   bonnie       1    7    7
twilight        elena        1    2    2
vampire diaries matt         1    5    5
zombie          enzo         1   14   14

#pivot

In [ ]:
pivot=df.pivot_table(
    index='series',
    columns='cast',
    values='properties',
    aggfunc='mean'
)
pivot

cast,bonnie,damon,elena,elijah,enzo,jermey,klaus,marcel,matt,rebekah,stefan,tyler
series,,,,,,,,,,,,
arafta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,NaN
first frost,NaN,NaN,NaN,NaN,NaN,NaN,32.0,NaN,NaN,NaN,NaN,NaN
got,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
israel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,NaN,NaN,NaN,NaN
meg,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN
my demon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0
shore,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN
sunlight,NaN,NaN,NaN,68.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
the originals,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
twilight,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
vampire diaries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN
zombie,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#crosstab

In [ ]:
ct=pd.crosstab(df['series'],df['networth'])
ct

networth,1.0,2.0,2.5,2.8,6.0,9.0,10.0,11.0,12.0,13.5,15.0,25.0
series,,,,,,,,,,,,
arafta,0,0,0,0,0,0,1,0,0,0,0,0
first frost,0,0,0,0,0,0,0,1,0,0,0,0
got,0,0,0,0,0,1,0,0,0,0,0,0
israel,0,0,0,0,0,0,0,0,0,0,0,1
meg,0,0,0,0,1,0,0,0,0,0,0,0
my demon,0,0,0,1,0,0,0,0,0,0,0,0
shore,0,0,0,0,0,0,0,0,0,1,0,0
sunlight,0,0,0,0,0,0,0,0,0,0,1,0
the originals,0,0,1,0,0,0,0,0,0,0,0,0
twilight,1,0,0,0,0,0,0,0,0,0,0,0
vampire diaries,0,1,0,0,0,0,0,0,0,0,0,0
zombie,0,0,0,0,0,0,0,0,1,0,0,0

#merge

In [ ]:
import pandas as pd
dataset={
    'cast':['matt','bonnie','elena','jermey','damon','stefan','tyler','klaus','elijah','rebekah','enzo','marcel'],
    'series':['vampire diaries','the originals','twilight','meg','got','arafta','my demon','first frost','sunlight','shore','zombie','israel'],
    'networth':[2,2.5,1,6,9,10,2.8,11,15,13.5,12,25],
    'properties':[5,7,2,9,10,18,45,32,68,10,14,23]

}
df=pd.DataFrame(dataset)
df

       cast           series  networth  properties
0      matt  vampire diaries       2.0           5
1    bonnie    the originals       2.5           7
2     elena         twilight       1.0           2
3    jermey              meg       6.0           9
4     damon              got       9.0          10
5    stefan           arafta      10.0          18
6     tyler         my demon       2.8          45
7     klaus      first frost      11.0          32
8    elijah         sunlight      15.0          68
9   rebekah            shore      13.5          10
10     enzo           zombie      12.0          14
11   marcel           israel      25.0          23

In [ ]:
import pandas  as pd
Mydataset={
    'Name':["Likitha","Elena","Zoya","Rithu","Ponnu","Firoj"],
    'Rollno':[12,15,43,62,29,20],
    'Marks':[45,50,49,40,35,38],
    'Subject':["Telugu","English","Maths","Science","Telugu","Social"],
    'properties':[5,7,2,9,10,18]
}
myvar = pd.DataFrame(Mydataset)
myvar

      Name  Rollno  Marks  Subject  properties
0  Likitha      12     45   Telugu           5
1    Elena      15     50  English           7
2     Zoya      43     49    Maths           2
3    Rithu      62     40  Science           9
4    Ponnu      29     35   Telugu          10
5    Firoj      20     38   Social          18

In [ ]:
merge=pd.merge(df,myvar,on='properties')
merge

,cast,series,networth,properties,Name,Rollno,Marks,Subject
0,matt,vampire diaries,2.0,5,Likitha,12,45,Telugu
1,bonnie,the originals,2.5,7,Elena,15,50,English
2,elena,twilight,1.0,2,Zoya,43,49,Maths
3,jermey,meg,6.0,9,Rithu,62,40,Science
4,damon,got,9.0,10,Ponnu,29,35,Telugu
5,stefan,arafta,10.0,18,Firoj,20,38,Social
6,rebekah,shore,13.5,10,Ponnu,29,35,Telugu

In [ ]:
concat=pd.concat([df,myvar])
concat

,cast,series,networth,properties,Name,Rollno,Marks,Subject
0,matt,vampire diaries,2.0,5,NaN,NaN,NaN,NaN
1,bonnie,the originals,2.5,7,NaN,NaN,NaN,NaN
2,elena,twilight,1.0,2,NaN,NaN,NaN,NaN
3,jermey,meg,6.0,9,NaN,NaN,NaN,NaN
4,damon,got,9.0,10,NaN,NaN,NaN,NaN
5,stefan,arafta,10.0,18,NaN,NaN,NaN,NaN
6,tyler,my demon,2.8,45,NaN,NaN,NaN,NaN
7,klaus,first frost,11.0,32,NaN,NaN,NaN,NaN
8,elijah,sunlight,15.0,68,NaN,NaN,NaN,NaN
9,rebekah,shore,13.5,10,NaN,NaN,NaN,NaN
10,enzo,zombie,12.0,14,NaN,NaN,NaN,NaN
11,marcel,israel,25.0,23,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,5,Likitha,12.0,45.0,Telugu
1,NaN,NaN,NaN,7,Elena,15.0,50.0,English
2,NaN,NaN,NaN,2,Zoya,43.0,49.0,Maths
3,NaN,NaN,NaN,9,Rithu,62.0,40.0,Science
4,NaN,NaN,NaN,10,Ponnu,29.0,35.0,Telugu
5,NaN,NaN,NaN,18,Firoj,20.0,38.0,Social